# This workflow deploys Azure automation runbooks into Azure.

name: runbook automation using github actions

on:
  push:
    branches: ["master"]
    paths:
      - "scripts/automation/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
#       - uses: azure/login@v1
#         with:
#            creds: ${{ secrets.AZURE_CREDENTIALS }}

      # triggering runbooks
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
           # webhook_type: 'json-extended'
           method: POST
           webhook_url: "https://77be02fb-a47f-4fae-9136-8ebc849e4a0f.webhook.eus.azure-automation.net/webhooks?token=fi25gGvi2QvUJUutYUuERgyJzsBrVmAoeF7Euu3GwQk%3d"
           #webhook_secret: "!polu@123"
           data: ${{secrets.RUNBOOK_CREDENTIALS}}

      
      # Logout
#       - name: logout
#         run: |
#           az logout
